name: clib-hello-world-demo
version: 0.1.0
compiler:
  cc: gcc
  cflags: -Wall -Wextra -O2
  ldflags:
dependencies:
  clib-hello-world: "~> 0.1.1"
test:
  cflags: -Wall -Wextra
platforms:
  linux:
    cflags: -fPIC
    ldflags: -shared
  darwin:
    cflags: -fPIC
    ldflags: -dynamiclib
  windows:
    cc: cl
    cflags: /W4
    ldflags: /DLL